### ISSUE TITLE
The passwords must be hidden during 'change password'. 

### ISSUE THREAD

**Issue by ghost** [bartekpacia/mentorship-client#80] opened 2020-05-21 15:52 UTC
While changing my password, as a user, I wouldn't want my passwords (both current and new) to be visible. 

![passwordshow](https://user-images.githubusercontent.com/44665174/82577661-eb236d80-9ba8-11ea-9759-2d72b83274f0.png)

Changes should be made so that the passwords are not visible.

**Comment by techno-disaster** [comment] 2020-05-21 17:46
Closing now because it looks like a duplicate of #76 . Feel free to open it again incase i have missed something

**Closed as completed by techno-disaster** 2020-05-21 17:46 UTC
