### ISSUE TITLE
Add a cancel button to the “change password” alert box.

### ISSUE THREAD

**Issue by HaripriyaB** [bartekpacia/mentorship-client#64] opened 2020-05-13 19:21 UTC
## Description
As a user, I need a cancel button on change password alert box which can take me back if I prefer not to change my password.

## Screenshots of the issue
![Screenshot_2020-05-13-23-26-44-77_92746fe779a9c2c81c5c767d4a402904](https://user-images.githubusercontent.com/34762451/81855367-e5ac9e80-957c-11ea-9884-c30a84d2959f.png)

## Acceptance Criteria
- [ ] Include a cancel button left to submit button

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by isabelcosta** [comment] 2020-05-13 20:39
@HaripriyaB 👏 👏 👏 very good issue description!

**Comment by techno-disaster** [comment] 2020-05-13 23:02
@anitab-org/mentorship-flutter-maintainers-1 can i work on this?

**Comment by bartekpacia** [comment] 2020-05-13 23:57
I think this would be a good `First timers` issue because it's relatively easy. (And if no `first timer` decides to work on this in, say, a week, then it could be assigned to @Techno-Disaster )

**Comment by techno-disaster** [comment] 2020-05-13 23:59
> I think this would be a good `First timers` issue because it's relatively easy. (And if no `first timer` decides to work on this in, say, a week, then it could be assigned to @Techno-Disaster )

makes sense, i wish too see new people start contributing soon too.

**Comment by ghost** [comment] 2020-05-20 19:54
Can I try working on this, please? @isabelcosta , @bartekpacia

**Comment by HaripriyaB** [comment] 2020-05-20 19:57
sure @MaheKhan assigning to you.

**Comment by ghost** [comment] 2020-05-20 20:02
Thankyou, @HaripriyaB !

**Comment by MaheKhan** [comment] 2020-05-21 05:20
@bartekpacia , would you please help me a little?

**Comment by ghost** [comment] 2020-05-21 05:43
@bartekpacia , @HaripriyaB , @isabelcosta :

![cancel_button](https://user-images.githubusercontent.com/44665174/82527380-eed8d500-9b53-11ea-85be-3f25e5a95a3e.png)

Did it! Yayyyyyyyyyyyy!!!!! <3 :)
On clicking 'Cancel', the dialog box closes and the changes to password are not saved.

**Comment by HaripriyaB** [comment] 2020-05-21 05:54
@MaheKhan great you did it! 🥇 
Now can you issue a Pull Request mentioning this issue number #64 ?

**Comment by ghost** [comment] 2020-05-21 06:18
Hey, @HaripriyaB ! 
I am new to git and GitHub. 
I made a mistake, instead of making a PR, I made a commit. 
How do I undo the commit?

**Comment by ghost** [comment] 2020-05-21 06:46
Okay. I reverted the commit.

**Comment by techno-disaster** [comment] 2020-05-21 09:09
looks like i accidentally created a double of this at #76 . will change it to confirm password field issue only

**Comment by techno-disaster** [comment] 2020-05-21 09:25
also @MaheKhan sorry but this is a first timers only so you can't work on it. @HaripriyaB please check if a contributor has a PR open or merged before assigning them to a first timer

**Comment by HaripriyaB** [comment] 2020-05-21 09:27
> 
> 
> also @MaheKhan sorry but this is a first timers only so you can't work on it. @HaripriyaB please check if a contributor has a PR open or merged before assigning them to a first timer

oh that was my mistake. sorry about that!

**Comment by ghost** [comment] 2020-05-21 13:19
> @anitab-org/mentorship-flutter-maintainers-1 can i work on this?

Hey, @Techno-Disaster ! Funny how you didn't see this was a first-timer-only issue when you begged @bartekpacia to assign it to you 8 days ago.

**Comment by MaheKhan** [comment] 2020-05-21 13:20
> I think this would be a good First timers issue because it's relatively easy. (And if no first timer decides to work on this in, say, a week, then it could be assigned to @Techno-Disaster )

@Techno-Disaster , Even funnier that had I not requested to be assigned yesterday, this issue would have been assigned to you. And surely if we keep first timer aside, I am more deserving of this issue than you.

**Comment by ghost** [comment] 2020-05-21 13:26
> I think this would be a good First timers issue because it's relatively easy. (And if no first timer decides to work on this in, say, a week, then it could be assigned to @Techno-Disaster )

@Techno-Disaster , Even funnier that had I not requested to be assigned yesterday, this issue would have been assigned to you. And surely if we keep first timer aside, I am more deserving of this issue than you. You, who according to what your profile says, is a 'Pro'. 
I'll tell you what else you are, you are clever, greedy, cunning, and ambitious.  
You took three days to respond to my comments about my previous PR. You won't approve it and find faults in it, when there are none to be found. 
But today, when you had to unassign me, you were so quick to respond. Didn't take you three days this time! 
And congratulations to the maintainers @isabelcosta and @bartekpacia for always being absent and letting this clever, greedy person control everything. 
This was my first contributing experience, you people could have been encouraging and if not that you could atleast have been just. 
Wow, AnitaB.org, much about 'fairness' in tech and inclusion of women in technology!

**Comment by techno-disaster** [comment] 2020-05-21 13:53
> > I think this would be a good First timers issue because it's relatively easy. (And if no first timer decides to work on this in, say, a week, then it could be assigned to @Techno-Disaster )
> 
> @Techno-Disaster , Even funnier that had I not requested to be assigned yesterday, this issue would have been assigned to you. And surely if we keep first timer aside, I am more deserving of this issue than you. You, who according to what your profile says, is a 'Pro'.

I am sorry, but I only "asked" @bartekpacia  if I could work on it, we did not have a First timer badge on the issue at that time. I have no intention of working on this PR as i already have a issue assigned to me (#67). 
The "Pro" is just a "Github Education" badge and i have never flexed about it. 

> I'll tell you what else you are, you are clever, greedy, cunning, and ambitious.
> You took three days to respond to my comments about my previous PR. You won't approve it and find faults in it, when there are none to be found.
> But today, when you had to unassign me, you were so quick to respond. Didn't take you three days this time!

Reveiwing PRs takes more time than closing a PR/issue or unassigning someone. PR reviews can extend upto a week. It's good that you think there are no errors in your PR, but as a repo maintainer i have to make sure before i merge it.
Take a look at #57 #66 #69 #71 , these are older PR than your and are still waiting testing or reviewing.

> And congratulations to the maintainers @isabelcosta and @bartekpacia for always being absent and letting this clever, greedy person control everything.

Nothing is controlled by a single person alone here, not sure what you mean by this :/

> This was my first contributing experience, you people could have been encouraging and if not that you could atleast have been just.
> Wow, AnitaB.org, much about 'fairness' in tech and inclusion of women in technology!

By the way thanks for all the nice things you said about me :)
Sorry if I messed up your "contributing experience" .
cc : @mayburgos @annabauza @isabelcosta  Please look into this, I'm pretty sure i did everything according to the rules

**Comment by ghost** [comment] 2020-05-21 14:33
@Techno-Disaster
Yes. You did ruin my first contributing experience. 
Why did you have to unassign me when I had already invested time and solved the issue? 
Sure you wouldn't have been so careful about only a first timer getting this issue assigned to them, had I not requested assignment yesterday and YOU would have been assigned to the issue.

**Comment by ghost** [comment] 2020-05-21 14:36
Can you not imagine how discouraging it is when you are very new to open source contribution, you learn a new skill (flutter in this case) to solve issues for your favourite organization, you put in time and effort to solve an issue, you are excited about making a successful PR, and then you suddenly get unassigned!

**Comment by ghost** [comment] 2020-05-21 14:38
@Techno-Disaster 
You are the maintainer here, you could have been kinder to me and not unassigned and let me work on this issue! 
I am so new to this, I am as good as a first timer!

**Comment by techno-disaster** [comment] 2020-05-21 15:00
> @Techno-Disaster
> Yes. You did ruin my first contributing experience.
> Why did you have to unassign me when I had already invested time and solved the issue?
> Sure you wouldn't have been so careful about only a first timer getting this issue assigned to them, had I not requested assignment yesterday and YOU would have been assigned to the issue.

@MaheKhan If we allow this, then anyone will finish a PR and say we have already made the PR just assign it to me now. This is the exact opposite of how we are supposed to hande an issue.
Rules are rules, and technically your first contribution is issue #60 , PR #73 

> Can you not imagine how discouraging it is when you are very new to open source contribution, you learn a new skill (flutter in this case) to solve issues for your favourite organization, you put in time and effort to solve an issue, you are excited about making a successful PR, and then you suddenly get unassigned!

To be honest, it just feels like you are buttering up people to side you.

> @Techno-Disaster
> You are the maintainer here, you could have been kinder to me and not unassigned and let me work on this issue!
> I am so new to this, I am as good as a first timer!

Like i said earlier, sorry if i was harsh but what if a legit first timer wants to contribute? and sees all first timer issues are claimed by the so called "new to flutter" people who have already contributed?
PR #73 does has 152 addtions 102 deletions, so you won't be "so new" to this

**Comment by krypticallusion** [comment] 2020-05-21 15:12
Can i contribute? I am a noob at flutter. Started recently :nerd_face:

**Comment by ghost** [comment] 2020-05-21 15:19
>To be honest, it just feels like you are buttering up people to side you. 

I don't know which people you are talking about. I am speaking only with you. 

>@MaheKhan If we allow this, then anyone will finish a PR and say we have already made the PR just assign it to me now.
 No. I was first 'assigned'  then I made the PR. 

>Like i said earlier, sorry if i was harsh but what if a legit first timer wants to contribute? and sees all first timer issues are claimed by the so called "new to flutter" people who have already contributed?
PR #73 does has 152 addtions 102 deletions, so you won't be "so new" to this

But, according to what batrek promised you would have been assigned this issue had I not requested an assignment yesterday. You wouldn't have mind that, I'm sure. And you wouldn't have acted 'the savior of the first-timers' then.  
* sighs * 
You are only being defensive. And more defensive. I don't even want to continue this conversation with you anymore. 
Bye, @Techno-Disaster ! 
Have fun stealing other people's chances. FY.

**Comment by mayburgos** [comment] 2020-05-21 17:19
@MaheKhan Hello! 

This particular issue has been raised to the @anitab-org/admins attention. We really appreciate that you took the time to solve one of our issues. I'm really sorry to hear about you feeling disappointed about our processes. 

As a reminder, we follow a [Code of Conduct](https://github.com/anitab-org/mentorship-flutter/blob/develop/code_of_conduct.md). Our expected behavior lists: 
- Exercise consideration and respect in your speech and actions.
- Attempt collaboration before conflict.
- Refrain from demeaning, discriminatory, or harassing behavior and speech.

If you do not plan to follow our Code of Conduct, then we will not accept your contributions. If you continue to break our Code of Conduct, we will have to ban you from our organization. If you have any issues about our processes and the Code of Conduct we follow, please email them directly to opensource@anitab.org.

**Comment by HaripriyaB** [comment] 2020-06-10 18:24
@anitab-org/admins since these first-timers issues are stale for long time and we have most of the issues for first-timers only due to which other contributors are not able to claim issues. So can we(non-first-timers) take up these issues for now so that we can clear up the pending issues sooner to welcome new issues and PRs??

**Comment by isabelcosta** [comment] 2020-06-10 21:52
@HaripriyaB I would say give it a try to some :)

**Comment by techno-disaster** [comment] 2020-06-17 11:36
Moved to #97

**Closed as completed** 2020-07-02 20:20 UTC
Labels: Type: Enhancement, First Timers Only, Category: User Interface
