### ISSUE TITLE
Finish ProfilePage implementation

### ISSUE THREAD

**Issue by bartekpacia** [bartekpacia/mentorship-client#27] opened 2020-05-01 00:34 UTC
**Is your feature request related to a problem? Please describe.**
Currently changing `available to mentor` and `needs mentoring` on the **RelationPage** doesn't have any effect.

![demo](https://user-images.githubusercontent.com/40357511/80771596-40dd9a80-8b54-11ea-92d6-38823b86e9b4.gif)

**Describe the solution you'd like**
I'd like this to work. I'd love this to work and be nicely coded :)

**Additional context**
I remember I had some issues with this while speed-coding this app during GCI and finally forgot to finish this :) That's why it isn't already implemented.

**Comment by gaurivn** [comment] 2020-05-01 13:08
I would like to work on this issue.

**Comment by bartekpacia** [comment] 2020-05-01 16:19
I'm on mobile and can't assign you, but...feel assigned and good luck :)

**Comment by gaurivn** [comment] 2020-05-01 16:27
Thank you @bartekpacia , @isabelcosta

**Comment by gaurivn** [comment] 2020-05-07 13:32
The issue is on Profile page and not Relation page right, I am still working on it.

**Comment by bartekpacia** [comment] 2020-05-07 14:14
You're right @gaurivn. I should realy be more focused when doing stuff.

**Comment by techno-disaster** [comment] 2020-05-08 14:14
@bartekpacia how would we handle checkbox state in bloc? I was thinking we can create a custom stateful widget in a different class? so it can call setstate without rebulding the main page? 
Is this the right/optimal way?

**Comment by bartekpacia** [comment] 2020-05-08 19:26
I'd use BLoc pattern instead of `setState()`.  Working solution using`setState()` is much easier to code but using BLoC we'll have cleaner code and arch in general.

**Comment by bartekpacia** [comment] 2020-05-10 18:47
I was asked on the Mentorship Flutter setup session to fix this, so I'm assigning this to myself.

**Comment by bartekpacia** [comment] 2020-05-12 23:14
Well, after investigating this, I feel the weight of the technical debt I created while speed-coding this👀. The whole `ProfilePage` is just pure garbage.
The best part is that I feel I don't have enough knowledge / feel confident enough to come up with a proper solution for this. I'll do some advanced BLoC tutorials in the near future and then try to fix this.
Any help/ideas are appreciated.

**Comment by techno-disaster** [comment] 2020-05-13 09:08
we can always rebase to using setstate 👀

**Comment by bartekpacia** [comment] 2020-05-13 23:39
Yeah, we `could`, but I'd like this to follow best practices so people can learn something.

But maybe BLoC is too complex for this use-case. Idk honestly. Recently, in one of my personal projects I started using [provider](https://pub.dev/packages/provider) and it's awesome and introduces much less boilerplate than BLoC.
Do you have experience with provider @Techno-Disaster?

**Comment by techno-disaster** [comment] 2020-05-13 23:41
> Yeah, we `could`, but I'd like this to follow best practices so people can learn something.
> 
> But maybe BLoC is too complex for this use-case. Idk honestly. Recently, in one of my personal projects I started using [provider](https://pub.dev/packages/provider) and it's awesome and introduces much less boilerplate than BLoC.
> Do you have experience with provider @Techno-Disaster?

@bartekpacia sadly no. i have been planning to learn these since a month, but something keeps popping up, preventing me to learn it. Lets see if i can start it again this week 🙂

**Comment by bartekpacia** [comment] 2020-05-13 23:55
Sure, no problem! It's really complex topic IMO so don't hurry, take your time doing tutorials etc.
I'm currently busy too but this issue the back of my head.

**Comment by techno-disaster** [comment] 2020-05-30 11:09
@bartekpacia How does our app use bloc? 🤔 Like isn't the basic idea of bloc to prevent reloading the whole page and just update the changed data? Our app just rebuilds the whole page when we change tabs.

**Comment by bartekpacia** [comment] 2020-05-30 15:23
At the HomeScreen level, BLOC is simply used to maintain the current state (currenly opened screen) . I'm sure that we're probably not using all of its power, but unfortunately, I don't have time to learn it properly now.

**Comment by bartekpacia** [comment] 2020-05-30 15:24
There's definitely area for improvement.

**Comment by techno-disaster** [comment] 2020-06-03 17:48
After asking in a lot of groups and people i was finally able to get this to work. Huge thanks to @gaurav192 for helping me with this issue. 
@anitab-org/mentorship-flutter-maintainers Can i be assigned to this issue? ik its issued to @bartekpacia  but considering he is busy with his MLH work and that i have already got it to work can I be assigned to this as well? 
Thank You.

**Comment by bartekpacia** [comment] 2020-06-03 19:48
@Techno-Disaster Sure, I'll reassign you. Glad you figured this out :) and thanks for taking this from me

**Closed as completed** 2020-06-10 22:01 UTC
Labels: Type: Bug, Help Wanted
