### ISSUE TITLE
Internal Server error while logging in 

### ISSUE THREAD

**Issue by HaripriyaB** [bartekpacia/mentorship-client#33] opened 2020-05-01 16:48 UTC
**Describe the bug**
As a user,
When I attempt to login for the mentorship app it throws an internal server error and doesn't proceed further.

**To Reproduce**
1. Go to login page
2. Click on login after entering test credentials
3. See error snackbar toast

**Expected behavior**
Remove the error and proceed with login process to signin with the app.
**Screenshots**
![Screenshot_2020-05-01-21-04-05-55_92746fe779a9c2c81c5c767d4a402904](https://user-images.githubusercontent.com/34762451/80823082-87d19b80-8bf9-11ea-8103-3b87941400d7.png)

**Smartphone:**
Android 9.0 Oppo 2020

**Comment by isabelcosta** [comment] 2020-05-01 16:54
@Techno-Disaster this could or not be the same issue as the other, in terms of solution 🤷‍♀️

**Comment by techno-disaster** [comment] 2020-05-01 17:01
yes, should merge them? logging in and signing up in same issue. what do you think? @isabelcosta

**Comment by HaripriyaB** [comment] 2020-05-01 17:05
> 
> 
> yes, should merge them? logging in and signing up in same issue. what do you think? @isabelcosta

@Techno-Disaster  But How do we merge issues technically?

**Comment by techno-disaster** [comment] 2020-05-01 17:06
We can't merge, merge them xd. I meant should we manually make just 1 issue?

**Comment by HaripriyaB** [comment] 2020-05-01 17:08
> 
> 
> We can't merge, merge them xd. I meant should we manually make just 1 issue?

Oh that can be done ... @isabelcosta should we merge them or leave 'em as 2 separate issues?

**Comment by isabelcosta** [comment] 2020-05-01 17:10
It can be closed this one, and referred in the other #32 .
But first, are you sure they are the same problem? Do you know the problem? What is it? @Techno-Disaster

**Comment by techno-disaster** [comment] 2020-05-01 17:15
@isabelcosta I haven't checked it yet but I'm 97% sure these warnings are due to the same error. Maybe @bartekpacia  can tell us something?

**Comment by isabelcosta** [comment] 2020-05-01 17:19
I am 97.5% sure as well, but until we actually now, because I don't, I think its good to create the habit of creating issues when something is buggy. In this way, people are active here and things are documented. So, in my opinion, we can leave this open. 🤷‍♀️ @Techno-Disaster

**Comment by techno-disaster** [comment] 2020-05-01 17:27
sounds good. Lets keep them both open.

**Comment by bartekpacia** [comment] 2020-05-01 17:36
Currently I have no idea why this might be happening. Will look into this tonight.

**Comment by vibhuti019** [comment] 2020-05-02 16:14
Can I work on this issue ??

**Comment by isabelcosta** [comment] 2020-05-02 16:29
I would say yes :) cc @bartekpacia @Techno-Disaster 
Although, do you know what the problem is here? @vibhuti019

**Comment by bartekpacia** [comment] 2020-05-03 00:47
I logged out, I logged in, *it worked on my machine*. Idk what might be causing it. Maybe it has something to do with your specific credentials.

**Comment by isabelcosta** [comment] 2020-05-03 16:25
I think I will download and test this then get a look inside this flutter app 👀

**Comment by isabelcosta** [comment] 2020-05-03 16:33
@bartekpacia @HaripriyaB Tested and this went well for me as well.
1. Downloaded this apk: https://github.com/anitab-org/mentorship-flutter/blob/apk/app-release.apk
2. Logged in with ursula / 12345678
3. Got into the logged screens of the app.

<img src="https://user-images.githubusercontent.com/11148726/80919809-f29ee600-8d63-11ea-923e-011c32e0ed2f.jpeg" alt="My Profile screen" width="300"/>

**Comment by isabelcosta** [comment] 2020-05-03 16:35
I tested this on my phone which is not android 9 I think.
What could have gone wrong here 🤔 @HaripriyaB @bartekpacia @Techno-Disaster 
Should we test in this specific version? @HaripriyaB can you test on another device?

**Comment by techno-disaster** [comment] 2020-05-03 16:40
@isabelcosta  i tested it too, everything looks fine. 
Currently running Android 10

**Comment by HaripriyaB** [comment] 2020-05-03 16:56
@isabelcosta I think it works, I just now installed the apk from the link you sent:
![Screenshot_2020-05-03-22-48-15-61_92746fe779a9c2c81c5c767d4a402904](https://user-images.githubusercontent.com/34762451/80920882-43c4cf00-8d90-11ea-92ff-62ba32cccbbf.png)

**Comment by HaripriyaB** [comment] 2020-05-03 17:19
So for login I can close this issue now. Pls confirm @isabelcosta

**Comment by isabelcosta** [comment] 2020-05-03 17:22
Cool @HaripriyaB thank you for checking. But what apk did you test previously? The releases one? Is that updated @bartekpacia, the apk that is on releases ?

**Comment by HaripriyaB** [comment] 2020-05-03 17:25
@isabelcosta Earlier I was testing with the apk sent by May in Zulip. May be that was not the updated apk. Now there is no problem with Login and signup process.

**Comment by isabelcosta** [comment] 2020-05-03 17:26
The last release was on January 21, when we still had the AWS server I think, so please use the link I showed here to test then. @bartekpacia or @Techno-Disaster  can you release a new apk under releases?

**Comment by HaripriyaB** [comment] 2020-05-03 17:28
> 
> 
> The last release was on January 21, when we still had the AWS server I think, so please use the link I showed here to test then. @bartekpacia or @Techno-Disaster can you release a new apk under releases?

Yeah @isabelcosta I will use the apk from apk branch which is the updated one.

**Comment by techno-disaster** [comment] 2020-05-03 17:29
> The last release was on January 21, when we still had the AWS server I think, so please use the link I showed here to test then. @bartekpacia or @Techno-Disaster can you release a new apk under releases?

@isabelcosta  the last build was 3 hours ago, and no changes have been made to the code since then.

**Comment by techno-disaster** [comment] 2020-05-03 17:30
@isabelcosta we should add a i have used the latest app release to test, checkbox in the bug /feature report issue template. What do you think?

**Comment by isabelcosta** [comment] 2020-05-03 17:31
@Techno-Disaster i am talking about this releases tab: https://github.com/anitab-org/mentorship-flutter/releases
The apk on the `apk` branch is updated for sure :)

**Comment by HaripriyaB** [comment] 2020-05-03 17:35
> 
> 
> @Techno-Disaster i am talking about this releases tab: https://github.com/anitab-org/mentorship-flutter/releases
> The apk on the `apk` branch is updated for sure :)

Yes. The apk from branch apk is updated. But the apk under releases is old which I was using it to test earlier.

**Comment by techno-disaster** [comment] 2020-05-03 17:36
Uploading

**Comment by isabelcosta** [comment] 2020-05-03 17:38
@HaripriyaB you did everything well :) I was the one who pointed everyone to the old one ;) i just updated QA team about it :) this was important for us to understand that for now its best to use the one on the branch, which is the most up to date, while releases, might be sometimes outdated

**Comment by isabelcosta** [comment] 2020-05-03 17:39
y'all can close this then :)

**Comment by Techno-Disaster** [comment] 2020-05-03 17:42
> @HaripriyaB you did everything well :) I was the one who pointed everyone to the old one ;) i just updated QA team about it :) this was important for us to understand that for now its best to use the one on the branch, which is the most up to date, while releases, might be sometimes outdated
uploaded under releases tab. but i would recommend using the apk branch for the latest updates.

**Comment by techno-disaster** [comment] 2020-05-03 17:43
> @HaripriyaB you did everything well :) I was the one who pointed everyone to the old one ;) i just updated QA team about it :) this was important for us to understand that for now its best to use the one on the branch, which is the most up to date, while releases, might be sometimes outdated

Uploaded to the releases tab.But i would recommend downloading from the apk branch for the latest releases.

**Closed as completed by techno-disaster** 2020-05-03 17:43 UTC
Labels: Type: Bug, Status: Available

**Comment by vibhuti019** [comment] 2020-05-04 08:38
It is working for me as well I tested it on 9.0 and 8.0 in android emulator.
